# Generated by Django 5.2.1 on 2025-05-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='operation_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operations.operation'),
            preserve_default=False,
        ),
    ]
