# Generated by Django 5.2.1 on 2025-05-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_project_operation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='operation_name',
        ),
    ]
