# Generated by Django 5.2.1 on 2025-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_project_operation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
