# Generated by Django 5.2.1 on 2025-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_well'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_first_name', models.CharField(max_length=100)),
                ('crew_last_name', models.CharField(max_length=100)),
                ('crew_position', models.CharField(max_length=100)),
            ],
        ),
    ]
