# Generated by Django 5.2.1 on 2025-05-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_well_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.project'),
        ),
    ]
