# Generated by Django 5.2.1 on 2025-05-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_well_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='project_name',
        ),
        migrations.AddField(
            model_name='well',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='operations.project'),
        ),
    ]
