# Generated by Django 5.2.1 on 2025-05-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_remove_well_project_name_well_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='project',
        ),
    ]
