# Generated by Django 5.2.1 on 2025-05-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_remove_well_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.project')),
            ],
        ),
    ]
