# Generated by Django 5.2.1 on 2025-05-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_pra'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
