# Generated by Django 5.2.1 on 2025-05-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_well_project_name_alter_project_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='project_name',
        ),
        migrations.AddField(
            model_name='well',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='operations.project'),
        ),
    ]
