# Generated by Django 5.2.1 on 2025-05-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_remove_well_project_name_well_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='project',
        ),
        migrations.AddField(
            model_name='well',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.project'),
        ),
    ]
