# Generated by Django 5.2.1 on 2025-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='wells',
            field=models.ManyToManyField(blank=True, null=True, to='operations.well'),
        ),
    ]
