# Generated by Django 5.2.1 on 2025-05-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_crew_wells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='wells',
        ),
    ]
