# Generated by Django 5.2.1 on 2025-05-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_remove_crew_wells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='day_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_operator', to='operations.crew'),
        ),
        migrations.AddField(
            model_name='well',
            name='day_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_supervisor', to='operations.crew'),
        ),
        migrations.AddField(
            model_name='well',
            name='night_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_operator', to='operations.crew'),
        ),
        migrations.AddField(
            model_name='well',
            name='night_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_supervisor', to='operations.crew'),
        ),
        migrations.AddField(
            model_name='well',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee', to='operations.crew'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.position'),
        ),
    ]
