# Generated by Django 5.2.1 on 2025-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_position_well_day_operator_well_day_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='day_operator',
        ),
        migrations.RemoveField(
            model_name='well',
            name='day_supervisor',
        ),
        migrations.RemoveField(
            model_name='well',
            name='night_operator',
        ),
        migrations.RemoveField(
            model_name='well',
            name='night_supervisor',
        ),
        migrations.RemoveField(
            model_name='well',
            name='trainee',
        ),
        migrations.AddField(
            model_name='well',
            name='current_status',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
