# Generated by Django 5.2.1 on 2025-05-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_remove_well_day_operator_remove_well_day_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='id',
        ),
        migrations.AddField(
            model_name='crew',
            name='well_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.well'),
            preserve_default=False,
        ),
    ]
