# Generated by Django 5.2.1 on 2025-05-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_remove_crew_id_crew_well_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='well_ptr',
        ),
        migrations.AddField(
            model_name='crew',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
